export const CLEAR_PROBLEM_HIGHLIGHT_TIMER: string = 'CLEAR_PROBLEM_HIGHLIGHT_TIMER';
export const SET_PROBLEM_HIGHLIGHT_TIMER: string = 'SET_PROBLEM_HIGHLIGHT_TIMER';
export const SET_CURRENT_CONTESTANT: string = 'SET_CURRENT_CONTESTANT';
export const SET_CURRENT_PROBLEM: string = 'SET_CURRENT_PROBLEM';
