enum ScoreboardGetterEnum {
    GET_CONTEST = 'GET_CONTEST',
    GET_PROBLEMS = 'GET_PROBLEMS',
    GET_CONTESTANTS = 'GET_CONTESTANTS',
    GET_SUBMISSIONS = 'GET_SUBMISSIONS',
    GET_VERDICTS = 'GET_VERDICTS',
    GET_CURRENT_PROBLEM = 'GET_CURRENT_PROBLEM',
    GET_CURRENT_CONTESTANT = 'GET_CURRENT_CONTESTANT',
    GET_CURRENT_PROBLEM_INDEX = 'GET_CURRENT_PROBLEM_INDEX',
    GET_PROBLEM_HIGHLIGHT_TIMER = 'GET_PROBLEM_HIGHLIGHT_TIMER',
    GET_CLICK_COOL_DOWN = 'GET_CLICK_COOL_DOWN',
}

export default ScoreboardGetterEnum;