enum ScoreboardMutationEnum {
    SET_CONTEST = 'SET_CONTEST',
    SET_PROBLEMS = 'SET_PROBLEMS',
    SET_CONTESTANTS = 'SET_CONTESTANTS',
    SET_SUBMISSIONS = 'SET_SUBMISSIONS',
    SET_VERDICTS = 'SET_VERDICTS',
    SET_CURRENT_PROBLEM = 'SET_CURRENT_PROBLEM',
    SET_CURRENT_CONTESTANT = 'SET_CURRENT_CONTESTANT',
    SET_CURRENT_PROBLEM_INDEX = 'SET_CURRENT_PROBLEM_INDEX',
    SET_PROBLEM_HIGHLIGHT_TIMER = 'SET_PROBLEM_HIGHLIGHT_TIMER'
}

export default ScoreboardMutationEnum;